version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      #      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /Users/trienth/Documents/sb-projects/spj-demo-volume:/var/lib/postgresql/data
    restart: unless-stopped
